project:
  type: website
  output-dir: docs

website:
  title: "Taek_Blog"
  navbar:
    left:
      - text: "Home"
        file: profile2.qmd
    right:
      - about.qmd
    tools:
      - text: 'contact'
        icon: envelope 
        menu:
          - text: instagram
            icon: instagram
            href: https://www.instagram.com/keatgnus/
          - text: github
            icon: github
            href: https://github.com/keatgnus
  page-footer: 
    left: "Copyright 2023, Seongtaek"
format:
  html:
    theme: lux
    css: styles.css



