project:
  type: website
  output-dir: docs

website:
  title: "Taek_Blog"
  navbar:
    left: 
      - Lab.qmd
    right:
      - about.qmd
    tools:
      - icon: envelope 
        menu:
          - text: instagram
            icon: instagram
            href: https://www.instagram.com/keatgnus/
          - text: github
            icon: github
            href: https://github.com/keatgnus
  page-footer: 
    left: "Copyright 2023, Seongtaek"
format:
  html:
    theme:
      light: lux
      dark: [lux, theme_dark.scss]
    css: styles.css
    toc: true
    toc-depth: 4
    number-sections: true
    highlight-style: nord
    monofont: Latin Modern san;
