project:
  type: website
  output-dir: docs

website:
  title: "Taek_Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/keatgnus
      - icon: instagram
        href: https://www.instagram.com/keatgnus/
  sidebar:
    - title: "Contact"
      style: "docked"
      background: light
      contents:
        - icon: github
          href: https://github.com/keatgnus
        - icon: instagram
          href: https://www.instagram.com/keatgnus/


format:
  html:
    theme: lux
    css: styles.css



