project:
  type: website
  output-dir: docs

website:
  title: "Taek_Blog"
  navbar:
    right:
      - about.qmd
    tools:
      - text: contact
        icon: instagram 
        menu:
          - text: instagram
            icon: instagram
            href: https://www.instagram.com/keatgnus/
          - text: github
            icon: github
            href: https://github.com/keatgnus
format:
  html:
    theme: lux
    css: styles.css



