project:
  type: website
  output-dir: docs

website:
  title: "Taek_Blog"
  navbar:
    right:
      - about.qmd
  sidebar:
    tools:
      - icon: envelop
        menu:
          - icon: instagram
            text: instagram
            url:  https://www.instagram.com/keatgnus/
          - icon: github
            text: github
            url:  https://github.com/keatgnus
format:
  html:
    theme: lux
    css: styles.css



