project:
  type: website
  output-dir: docs

website:
  title: "Taek_Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/keatgnus
      - icon: instagram
        href: https://www.instagram.com/keatgnus/
format:
  html:
    toc: true
    theme: lux
    css: styles.css



