project:
  type: website
  output-dir: docs

website:
  title: "seongtaek Jo"
  navbar:
    right:
      - about.qmd
    tools:
      - icon: envelope
        text: contact
        menu:
          - text: instagram
            icon: instagram
            href: https://www.instagram.com/keatgnus/
          - text: github
            icon: github
            href: https://github.com/keatgnus
format:
  html:
    theme: lux
    css: styles.css



